# Generated by Django 5.0.6 on 2024-07-02 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='status',
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('guest', 'Guest'), ('employee', 'Employee')], default='guest', max_length=50),
        ),
    ]
