services:

  backend:
    build: ./backend
    volumes:
      - ./backend:/usr/src/app
      - ./backend/static:/usr/src/app/static
    expose:
      - 8000

  frontend:
    stdin_open: true
    build: ./frontend
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    expose:
      - 5173
    environment:
      - NODE_ENV=development
    depends_on:
      - backend

  reverse_proxy:
    build: ./nginx
    ports:
      - 81:80
    volumes:
      - ./backend/static:/static
    depends_on:
      - backend
      - frontend